// Code generated by "kod generate". DO NOT EDIT.
//go:build !ignoreKodGen

package server

import (
	"context"
	"github.com/go-kod/kod"
	"github.com/go-kod/kod/interceptor"
	"github.com/jhump/protoreflect/desc"
	"github.com/nautilus/graphql"
	"github.com/sysulq/graphql-gateway/pkg/generator"
	"github.com/vektah/gqlparser/v2/ast"
	"google.golang.org/protobuf/runtime/protoiface"
	"net/http"
	"reflect"
)

func init() {
	kod.Register(&kod.Registration{
		Name:      "github.com/sysulq/graphql-gateway/pkg/server/Caller",
		Interface: reflect.TypeOf((*Caller)(nil)).Elem(),
		Impl:      reflect.TypeOf(caller{}),
		Refs:      `⟦5f5ebf18:KoDeDgE:github.com/sysulq/graphql-gateway/pkg/server/Caller→github.com/sysulq/graphql-gateway/pkg/server/ConfigComponent⟧`,
		LocalStubFn: func(ctx context.Context, info *kod.LocalStubFnInfo) any {
			interceptors := info.Interceptors
			if h, ok := info.Impl.(interface {
				Interceptors() []interceptor.Interceptor
			}); ok {
				interceptors = append(interceptors, h.Interceptors()...)
			}

			return caller_local_stub{
				impl:        info.Impl.(Caller),
				interceptor: interceptor.Chain(interceptors),
				name:        info.Name,
			}
		},
	})
	kod.Register(&kod.Registration{
		Name:      "github.com/sysulq/graphql-gateway/pkg/server/ConfigComponent",
		Interface: reflect.TypeOf((*ConfigComponent)(nil)).Elem(),
		Impl:      reflect.TypeOf(Config{}),
		Refs:      ``,
		LocalStubFn: func(ctx context.Context, info *kod.LocalStubFnInfo) any {
			interceptors := info.Interceptors
			if h, ok := info.Impl.(interface {
				Interceptors() []interceptor.Interceptor
			}); ok {
				interceptors = append(interceptors, h.Interceptors()...)
			}

			return configComponent_local_stub{
				impl:        info.Impl.(ConfigComponent),
				interceptor: interceptor.Chain(interceptors),
				name:        info.Name,
			}
		},
	})
	kod.Register(&kod.Registration{
		Name:      "github.com/sysulq/graphql-gateway/pkg/server/Queryer",
		Interface: reflect.TypeOf((*Queryer)(nil)).Elem(),
		Impl:      reflect.TypeOf(queryer{}),
		Refs: `⟦80ad5dbf:KoDeDgE:github.com/sysulq/graphql-gateway/pkg/server/Queryer→github.com/sysulq/graphql-gateway/pkg/server/Registry⟧,
⟦a8d89257:KoDeDgE:github.com/sysulq/graphql-gateway/pkg/server/Queryer→github.com/sysulq/graphql-gateway/pkg/server/Caller⟧`,
		LocalStubFn: func(ctx context.Context, info *kod.LocalStubFnInfo) any {
			interceptors := info.Interceptors
			if h, ok := info.Impl.(interface {
				Interceptors() []interceptor.Interceptor
			}); ok {
				interceptors = append(interceptors, h.Interceptors()...)
			}

			return queryer_local_stub{
				impl:        info.Impl.(Queryer),
				interceptor: interceptor.Chain(interceptors),
				name:        info.Name,
			}
		},
	})
	kod.Register(&kod.Registration{
		Name:      "github.com/sysulq/graphql-gateway/pkg/server/Registry",
		Interface: reflect.TypeOf((*Registry)(nil)).Elem(),
		Impl:      reflect.TypeOf(repository{}),
		Refs:      `⟦81f122f0:KoDeDgE:github.com/sysulq/graphql-gateway/pkg/server/Registry→github.com/sysulq/graphql-gateway/pkg/server/Caller⟧`,
		LocalStubFn: func(ctx context.Context, info *kod.LocalStubFnInfo) any {
			interceptors := info.Interceptors
			if h, ok := info.Impl.(interface {
				Interceptors() []interceptor.Interceptor
			}); ok {
				interceptors = append(interceptors, h.Interceptors()...)
			}

			return registry_local_stub{
				impl:        info.Impl.(Registry),
				interceptor: interceptor.Chain(interceptors),
				name:        info.Name,
			}
		},
	})
	kod.Register(&kod.Registration{
		Name:      "github.com/sysulq/graphql-gateway/pkg/server/ServerComponent",
		Interface: reflect.TypeOf((*ServerComponent)(nil)).Elem(),
		Impl:      reflect.TypeOf(server{}),
		Refs: `⟦fa17661a:KoDeDgE:github.com/sysulq/graphql-gateway/pkg/server/ServerComponent→github.com/sysulq/graphql-gateway/pkg/server/ConfigComponent⟧,
⟦9bbf643d:KoDeDgE:github.com/sysulq/graphql-gateway/pkg/server/ServerComponent→github.com/sysulq/graphql-gateway/pkg/server/Caller⟧,
⟦f1ffc65c:KoDeDgE:github.com/sysulq/graphql-gateway/pkg/server/ServerComponent→github.com/sysulq/graphql-gateway/pkg/server/Queryer⟧,
⟦906c61f4:KoDeDgE:github.com/sysulq/graphql-gateway/pkg/server/ServerComponent→github.com/sysulq/graphql-gateway/pkg/server/Registry⟧`,
		LocalStubFn: func(ctx context.Context, info *kod.LocalStubFnInfo) any {
			interceptors := info.Interceptors
			if h, ok := info.Impl.(interface {
				Interceptors() []interceptor.Interceptor
			}); ok {
				interceptors = append(interceptors, h.Interceptors()...)
			}

			return serverComponent_local_stub{
				impl:        info.Impl.(ServerComponent),
				interceptor: interceptor.Chain(interceptors),
				name:        info.Name,
			}
		},
	})
}

// kod.InstanceOf checks.
var _ kod.InstanceOf[Caller] = (*caller)(nil)
var _ kod.InstanceOf[ConfigComponent] = (*Config)(nil)
var _ kod.InstanceOf[Queryer] = (*queryer)(nil)
var _ kod.InstanceOf[Registry] = (*repository)(nil)
var _ kod.InstanceOf[ServerComponent] = (*server)(nil)

// Local stub implementations.

type caller_local_stub struct {
	impl        Caller
	name        string
	interceptor interceptor.Interceptor
}

// Check that caller_local_stub implements the Caller interface.
var _ Caller = (*caller_local_stub)(nil)

func (s caller_local_stub) Call(ctx context.Context, a1 *desc.MethodDescriptor, a2 protoiface.MessageV1) (r0 protoiface.MessageV1, err error) {

	if s.interceptor == nil {
		r0, err = s.impl.Call(ctx, a1, a2)
		return
	}

	call := func(ctx context.Context, info interceptor.CallInfo, req, res []any) (err error) {
		r0, err = s.impl.Call(ctx, a1, a2)
		res[0] = r0
		return
	}

	info := interceptor.CallInfo{
		Impl:       s.impl,
		Component:  s.name,
		FullMethod: "github.com/sysulq/graphql-gateway/pkg/server/Caller.Call",
		Method:     "Call",
	}

	err = s.interceptor(ctx, info, []any{a1, a2}, []any{r0}, call)
	return
}

func (s caller_local_stub) GetDescs() (r0 []*desc.FileDescriptor) {
	// Because the first argument is not context.Context, so interceptors are not supported.
	r0 = s.impl.GetDescs()
	return
}

type configComponent_local_stub struct {
	impl        ConfigComponent
	name        string
	interceptor interceptor.Interceptor
}

// Check that configComponent_local_stub implements the ConfigComponent interface.
var _ ConfigComponent = (*configComponent_local_stub)(nil)

func (s configComponent_local_stub) Config() (r0 *Config) {
	// Because the first argument is not context.Context, so interceptors are not supported.
	r0 = s.impl.Config()
	return
}

type queryer_local_stub struct {
	impl        Queryer
	name        string
	interceptor interceptor.Interceptor
}

// Check that queryer_local_stub implements the Queryer interface.
var _ Queryer = (*queryer_local_stub)(nil)

func (s queryer_local_stub) Query(ctx context.Context, a1 *graphql.QueryInput, a2 interface{}) (err error) {

	if s.interceptor == nil {
		err = s.impl.Query(ctx, a1, a2)
		return
	}

	call := func(ctx context.Context, info interceptor.CallInfo, req, res []any) (err error) {
		err = s.impl.Query(ctx, a1, a2)
		return
	}

	info := interceptor.CallInfo{
		Impl:       s.impl,
		Component:  s.name,
		FullMethod: "github.com/sysulq/graphql-gateway/pkg/server/Queryer.Query",
		Method:     "Query",
	}

	err = s.interceptor(ctx, info, []any{a1, a2}, []any{}, call)
	return
}

type registry_local_stub struct {
	impl        Registry
	name        string
	interceptor interceptor.Interceptor
}

// Check that registry_local_stub implements the Registry interface.
var _ Registry = (*registry_local_stub)(nil)

func (s registry_local_stub) FindFieldByName(a0 desc.Descriptor, a1 string) (r0 *desc.FieldDescriptor) {
	// Because the first argument is not context.Context, so interceptors are not supported.
	r0 = s.impl.FindFieldByName(a0, a1)
	return
}

func (s registry_local_stub) FindGraphqlFieldByProtoField(a0 *ast.Definition, a1 string) (r0 *ast.FieldDefinition) {
	// Because the first argument is not context.Context, so interceptors are not supported.
	r0 = s.impl.FindGraphqlFieldByProtoField(a0, a1)
	return
}

func (s registry_local_stub) FindMethodByName(a0 ast.Operation, a1 string) (r0 *desc.MethodDescriptor) {
	// Because the first argument is not context.Context, so interceptors are not supported.
	r0 = s.impl.FindMethodByName(a0, a1)
	return
}

func (s registry_local_stub) FindObjectByFullyQualifiedName(a0 string) (r0 *desc.MessageDescriptor, r1 *ast.Definition) {
	// Because the first argument is not context.Context, so interceptors are not supported.
	r0, r1 = s.impl.FindObjectByFullyQualifiedName(a0)
	return
}

func (s registry_local_stub) FindObjectByName(a0 string) (r0 *desc.MessageDescriptor) {
	// Because the first argument is not context.Context, so interceptors are not supported.
	r0 = s.impl.FindObjectByName(a0)
	return
}

func (s registry_local_stub) FindUnionFieldByMessageFQNAndName(a0 string, a1 string) (r0 *desc.FieldDescriptor) {
	// Because the first argument is not context.Context, so interceptors are not supported.
	r0 = s.impl.FindUnionFieldByMessageFQNAndName(a0, a1)
	return
}

func (s registry_local_stub) SchemaDescriptorList() (r0 generator.SchemaDescriptorList) {
	// Because the first argument is not context.Context, so interceptors are not supported.
	r0 = s.impl.SchemaDescriptorList()
	return
}

type serverComponent_local_stub struct {
	impl        ServerComponent
	name        string
	interceptor interceptor.Interceptor
}

// Check that serverComponent_local_stub implements the ServerComponent interface.
var _ ServerComponent = (*serverComponent_local_stub)(nil)

func (s serverComponent_local_stub) BuildServer(ctx context.Context) (r0 http.Handler, err error) {

	if s.interceptor == nil {
		r0, err = s.impl.BuildServer(ctx)
		return
	}

	call := func(ctx context.Context, info interceptor.CallInfo, req, res []any) (err error) {
		r0, err = s.impl.BuildServer(ctx)
		res[0] = r0
		return
	}

	info := interceptor.CallInfo{
		Impl:       s.impl,
		Component:  s.name,
		FullMethod: "github.com/sysulq/graphql-gateway/pkg/server/ServerComponent.BuildServer",
		Method:     "BuildServer",
	}

	err = s.interceptor(ctx, info, []any{}, []any{r0}, call)
	return
}
