// Code generated by kod struct2interface; DO NOT EDIT.

package server

import (
	"context"
	"net/http"

	"github.com/golang/protobuf/proto"
	"github.com/jhump/protoreflect/desc"
	"github.com/nautilus/graphql"
	"github.com/sysulq/graphql-gateway/pkg/generator"
)

// Config is a component that implements ConfigComponent.
type ConfigComponent interface {
	Config() *Config
}

// server is a component that implements ServerComponent.
type ServerComponent interface {
	BuildServer(ctx context.Context) (http.Handler, error)
}

// caller is a component that implements Caller.
type Caller interface {
	GetDescs() []*desc.FileDescriptor
	Call(ctx context.Context, rpc *desc.MethodDescriptor, message proto.Message) (proto.Message, error)
}

// queryer is a component that implements Queryer.
type Queryer interface {
	SetPM(pm generator.Registry)
	Query(ctx context.Context, input *graphql.QueryInput, result interface{}) error
}
