// Code generated by "kod generate". DO NOT EDIT.
//go:build !ignoreKodGen

package main

import (
	"github.com/go-kod/kod"
	"reflect"
)

// Full method names for components.
const ()

func init() {
	kod.Register(&kod.Registration{
		Name:      "github.com/go-kod/kod/Main",
		Interface: reflect.TypeOf((*kod.Main)(nil)).Elem(),
		Impl:      reflect.TypeOf(app{}),
		Refs: `⟦c03c7479:KoDeDgE:github.com/go-kod/kod/Main→github.com/go-kod/grpc-gateway/internal/config/Config⟧,
⟦f4859030:KoDeDgE:github.com/go-kod/kod/Main→github.com/go-kod/grpc-gateway/internal/server/Gateway⟧`,
		LocalStubFn: nil,
	})
}

// kod.InstanceOf checks.
var _ kod.InstanceOf[kod.Main] = (*app)(nil)

// Local stub implementations.
