// Code generated by kod struct2interface; DO NOT EDIT.

package generator

import (
	"github.com/jhump/protoreflect/desc"
	"github.com/vektah/gqlparser/v2/ast"
)

// repository is a component that implements Registry.
type Registry interface {
	FindMethodByName(op ast.Operation, name string) *desc.MethodDescriptor
	FindObjectByName(name string) *desc.MessageDescriptor
	FindObjectByFullyQualifiedName(fqn string) (*desc.MessageDescriptor, *ast.Definition)
	FindFieldByName(msg desc.Descriptor, name string) *desc.FieldDescriptor
	FindUnionFieldByMessageFQNAndName(fqn, name string) *desc.FieldDescriptor
	FindGraphqlFieldByProtoField(msg *ast.Definition, name string) *ast.FieldDefinition
}
