// Code generated by "kod generate"; DO NOT EDIT.

package config

// Config is implemented by [config],
// which can be mocked with [NewMockConfig].
type Config interface {
	// Config is implemented by [config.Config]
	Config() *ConfigInfo
}
