// Code generated by kod struct2interface; DO NOT EDIT.

package generator

import (
	"github.com/jhump/protoreflect/desc"
	"google.golang.org/protobuf/compiler/protogen"
)

// generator is a component that implements Generator.
type Generator interface {
	NewSchemas(descs []*desc.FileDescriptor, mergeSchemas, genServiceDesc bool, plugin *protogen.Plugin) (schemas SchemaDescriptorList, err error)
}
